### ISSUE TITLE
ARM A64 literal value is parsed as a comment

### ISSUE THREAD

**Issue by maxcnunes** [RubixDev/tree-sitter-asm#9]
ARM A64 instruction set uses `#` prefix to represent literal values. Here is a valid example of assembly for Apply M1 processor:

```asm
.global _main
.align 4

_main:
    mov X0, #1          ; arg[0] = 1 = STDOUT
    adr X1, helloworld  ; arg[1] = string to pring
    mov X2, #16         ; arg[2] = length of our string
    mov X16, #4         ; Unix write system call

    mov X0, #0          ; Use 0 return code
    mov X16, #2         ; Unix exit system call
    svc #0xFFFF         ; call kernel to end program

helloworld: .ascii "Hello M1-World!\n"
```

This is how it looks for me on neovim:

<img width="478" alt="Screenshot 2024-03-16 at 17 59 53" src="https://github.com/RubixDev/tree-sitter-asm/assets/680356/b145ad7d-7f76-44b8-9fd5-4193c626f700">

This is happening because of this configuration https://github.com/RubixDev/tree-sitter-asm/blob/6ace266be7ad6bf486a95427ca3fc949aff66211/grammar.js#L67. Since `#` can be a comment for other architectures, we could come up with a solution where it treats `#` either as a number or other identifier when it is the second argument of an instruction maybe.

References:
- [Loading data into registers](https://developer.arm.com/documentation/107829/0200/Assembly-language-basics/Loading-data-into-registers)
- [MOV (wide immediate)](https://developer.arm.com/documentation/ddi0602/2022-09/Base-Instructions/MOV--wide-immediate---Move--wide-immediate---an-alias-of-MOVZ-)
- [Differences between Assembly Languages](https://stackoverflow.com/questions/64122200/differences-between-assembly-languages)

**Comment by maxcnunes** [comment]
The Negative Lookbehind matching works if we take just a single space in consideration:

```
(\/\/|((?<!,\s)#.*)|;).*
```

<img width="604" alt="Screenshot 2024-03-16 at 19 09 57" src="https://github.com/RubixDev/tree-sitter-asm/assets/680356/ccb5cef1-2bd7-4aed-a41a-21ad80e00dd6">


But it is possible to have more spaces, so it isn't a good solution. And if I try to add a `*` to count for that, it breaks the regex:
```
(\/\/|((?<!,\s*)#.*)|;).*
```

> Error: * A quantifier inside a lookbehind makes it non-fixed width

**Comment by maxcnunes** [comment]
I tried a few things, but I have not got to a solution yet. I just asked for help on https://github.com/tree-sitter/tree-sitter/discussions/3190.

**Comment by maxcnunes** [comment]
So, I found a solution by removing comments from the extras configuration. More details on https://github.com/tree-sitter/tree-sitter/discussions/3190#discussioncomment-8822346.

**Comment by maxcnunes** [comment]
On my short example to solve that hash problem in the tree-sitter discussion that I linked above, which a hash symbol can be either a comment or immediate data. I was using a shorter parser implementation with a more strict rule, defining the rules based on the instruction name.
Once I tried to move the fixing described on that discussion, which is moving line comments rule out of the extras configuration, and applying it to this project, which uses a more generic parsing, not depending exactly on each instruction rule individually. The solution didn't work quite well. Then I tried to adapt this project to be less generic, and break some rules based on the assembler architecture (GAS, MIPS, ARM, and etc). That helped to solve the comment issue again. But I noticed another issue, that handling multiple architecture syntax at the same file is quite complicated. Specially because the order of instruction arguments can change between architectures. For instance, these are all instructions to run a write system call:

| Arch | Code | Definition |
| ---- | ----- | ----------- |
| ARM | `mov X16, #4` | `<instruction> <register> <immediate_data>` |
| MIPS | `li $v0, 4` | `<instruction> <register> <immediate_data>` |
| GAS | `movl $4, %eax` | `<instruction> <immediate_data> <register>` |

As we can see, MIPS and GAS both use $ prefix as an identifier, but one uses it for registers and the other for immediate data, and even worse, they use it opposite orders. So, it seems impossible based on each line individually to properly distinguish which architecture syntax to use and proper identify the data types for each part.

So, I am wondering what is the best solution here. It seems in order for the parser to be more precise, each file should have its own parser. It could be either a completely different project or we could break the root of this grammar into multiple architectures support, and use a comment at the top of the file to define which grammar to use. I like the second option, because having a single ASM project for every syntax support could be easier to maintain, they could share common rules, or even just by having them closer could be simpler to apply common fixing or improvement for them.

About the comment to define the architecture at the top of the file, the Flow language does that too `// @flow` https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow, it seems like a nice trick to solve cases like this.

What do you think? Any suggestions?

If you rather keep this project generic and with a few false positives like those, that is fine, I could create a separate project for this other solution.

cc @RubixDev

**Comment by RubixDev** [comment]
Thanks for all the work and detailed description you already put here! I think I got it working with the latest commit. Could you please verify it is working as you expect it to?

---

> The Negative Lookbehind matching works if we take just a single space in consideration:

Look-around isn't supported by tree-sitter anyway.

> So, I found a solution by removing comments from the extras configuration. More details on https://github.com/tree-sitter/tree-sitter/discussions/3190#discussioncomment-8822346.

I want to keep comments in the extras though, manually having to handle that is a huge hassle.

> So, I am wondering what is the best solution here. It seems in order for the parser to be more precise, each file should have its own parser. It could be either a completely different project or we could break the root of this grammar into multiple architectures support, and use a comment at the top of the file to define which grammar to use. I like the second option, because having a single ASM project for every syntax support could be easier to maintain, they could share common rules, or even just by having them closer could be simpler to apply common fixing or improvement for them.

I know this parser is error prone, but that's sort of by design. All I want to achieve with it is a good enough parser for syntax highlighting that's general enough for supporting most well known asm dialects. It was clear from the start that conflicts like this one would arise, yet I don't plan to split the parser into several specific ones. Also something like that is already in the works by amaanq: https://github.com/nvim-treesitter/nvim-treesitter/pull/5946#issuecomment-1935086929.

**Comment by maxcnunes** [comment]
hi @RubixDev thanks for taking a look. Got it, your goal with this project makes sense. And thanks for referencing that other project.
About your fixing, it does make `#` literal numbers work, while supporting it for comments as well. But it seems to have broken the existing tests. I noticed the CI for your PR passed, but when I run the tests locally it is failing, looks like the CI didn't actually ran those tests at all.

**Comment by RubixDev** [comment]
Thanks for pointing that out. Seems like tree-sitter changed where tests have to be stored, so none of the tests actually ran. I think I properly fixed it now though.
